from pyforged.__errors__ import PyForgedException, exception_handler

class BedrockedException(PyForgedException):
    pass